### ISSUE TITLE
Postprocessor: fallback keyword initial

### ISSUE THREAD

**Issue by iamvdo** [iamvdo/pleeease#10]
Add a postprocessor for `initial` keyword. For example,

``` css
.e {
    font-size: initial;
}
```

will be converted to:

``` css
.e {
    font-size: medium;
}
```

`initial` isn't supported in IE, even in IE11.

Troublesome:
- when initial values depend on UAs (`color` for example, even if black is a standard de facto)
- when initial values are contextual (`text-align` is `left` or `right` based on `direction`, etc.)
