### ISSUE TITLE
Postprocessor: fallback opacity

### ISSUE THREAD

**Issue by iamvdo** [iamvdo/pleeease#16]
Add a fallback `opacity` for IE.

This

``` css
.e {
    opacity: .5;
}
```

has to be converted like so:

``` css
.e {
    opacity: .5;
    filter: alpha(opacity=50);
}
```

https://developer.mozilla.org/fr/docs/Web/CSS/opacity
