### ISSUE TITLE
import with url('../folder')

### ISSUE THREAD

**Issue by vporoshok** [iamvdo/pleeease#34]
I use bower for standard libs like font awesome. Bower place files in `/static/vendor/` folder, then I just add line
```css
@import url('../vendor/font-awesome/css/font-awesome.css');
```
in my `style.css`. And I have a problem: in `font-awesome.css` fonts including by relative path:
```css
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.3.0');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.3.0') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff2?v=4.3.0') format('woff2'), url('../fonts/fontawesome-webfont.woff?v=4.3.0') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.3.0') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.3.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
Well, `pleeease` concat this with my styles and put result in `/static/css/style.css`. Then browsers try to load fonts from `/static/fonts` except `/static/vendor/font-awesome/fonts/`.

If exist any more right way to do this with no errors I glad to try it. By the other side I would ask you to improve import method to overwrite relative path in including code, like a `../vendor/font-awesome/css/../fonts/...`.
