### ISSUE TITLE
Duplication de @import

### ISSUE THREAD

**Issue by raphaelgoetter** [iamvdo/pleeease#4]
En employant l'import de pleeease, mes styles sont dupliqués.

config.css : 

``` css
:root {
    --basefont: helvetica;
    font-size: 62.5%;
}
```

styles.css : 

``` css
@import url("config.css");

body {
    font-size: 2rem;
    font-family: var(--basefont);
    display: flex;
    order: 2;
}
```

.pleeeaserc : 

``` js
{
    "output": "styles.min.css",
    "fallbacks": {
        "autoprefixer": true,
        "variables": true,
        "rem": ["62.5%", {"replace": false}],
        "pseudoElements": true
    },
    "optimizers": {
        "import": true,
        "minifier": false,
        "mqpacker": true
    }
}
```

J'ai exécuté `pleeease watch`

**Résultat :** 

styles.min.css : 

``` css
:root {
    --basefont: helvetica;
    font-size: 62.5%;
}
:root {
    --basefont: helvetica;
    font-size: 62.5%;
}

body {
    font-size: 20px;
    font-size: 2rem;
    font-family: helvetica;
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-ordinal-group: 3;
    -webkit-order: 2;
    -ms-flex-order: 2;
    order: 2;
}
```
