### ISSUE TITLE
Source Maps Ignoring Custom Properties In Some Circumstances

### ISSUE THREAD

**Issue by jupl** [iamvdo/pleeease#45]
```js
// .pleeeaserc
{
  "next": {
    "customProperties": true
  },
  "sourcemaps": true
}
```

```css
/* a.css */
@import './b.css';
body { color: var(--color); }
```

```css
/* b.css */
:root { --color: red; }
````

Given the files, when I compile `a.css`, in the source maps `b.css` is not there. It does appear when `{preserve: true}` is set for `customProperties`.
