### ISSUE TITLE
Idée d'amélioration : fallback pour calc()

### ISSUE THREAD

**Issue by raphaelgoetter** [iamvdo/pleeease#6]
Hello,

[Myth](http://www.myth.io/) propose le fallback `calc`suivant : 

Input : 

``` css
pre {
  margin: calc(var(--large) * 2);
}
```

Output : 

``` css
pre {
  margin: 20px;
}
```

Je pense que Myth est un peu trop bourrin et que sa façon de faire est risquée. Mais on pourrait bénéficier du fallback quand-même (qui permettrait d'utiliser `calc` sur IE8 et surtout sur Android <4.4)

Suggestion d'output avec fallback : 

``` css
pre {
  margin: 20px;
  margin: calc(var(--large) * 2);
}
```

Inconvénient : lourdeur du code produit :/
