### ISSUE TITLE
compiling issues with comments

### ISSUE THREAD

**Issue by Kayu84** [iamvdo/pleeease#88]
I've wrote an "how to use pleeease.io" workflow charts (at the bottom of this issue) if using scss with comments, because there is a Bug with Linecomments over Css-selectors.

how you can reproduce this issue:
following code can't be compiled:
```css
body.skin {
  #normal-content  #{
    > div {
      &:nth-of-type(even) {
        .news-latest-container {
        //  article {
        //    .news-latest-image {
        //      background-color: $content-background;
        //      border: 1px solid $box-shadow;
        //    }
        //  }
        }
      }
    }
    .sb-icon {
      .row {
        -webkit-flex-flow: row wrap;
        -ms-flex-flow: row wrap;
        flex-flow: row wrap;
        .col-sm-3 {
          align-items: flex-start;
        }
      }
    }
  }
}
```

changing it into one of the follwing codes works:
```css
body.skin {
  #normal-content {
    > div {
      &:nth-of-type(even) {
        .news-latest-container {
          article {
            .news-latest-image {
        //      background-color: $content-background;
        //      border: 1px solid $box-shadow;
            }
          }
        }
      }
    }
    .sb-icon {
      .row {
        -webkit-flex-flow: row wrap;
        -ms-flex-flow: row wrap;
        flex-flow: row wrap;
        .col-sm-3 {
          align-items: flex-start;
        }
      }
    }
  }
}
```
```css
body.skin {
  #normal-content {
    > div {
      &:nth-of-type(even) {
        .news-latest-container {
        /*  article {
            .news-latest-image {
              background-color: $content-background;
              border: 1px solid $box-shadow;
            }
          }*/
        }
      }
    }
    .sb-icon {
      .row {
        -webkit-flex-flow: row wrap;
        -ms-flex-flow: row wrap;
        flex-flow: row wrap;
        .col-sm-3 {
          align-items: flex-start;
        }
      }
    }
  }
}
```

> pls don't use linecomments like blockcomments
> ```css
> //
> // code
> //
> ```
> the prefix extender pleeease.io can't work with it and the complete code cannot be parsed.
> 
> if you using phpstorm strg+/ use strg+shift+/ instead, so we using blockcomments like
> ```css
> /*
>   code
> */
> ```
> // can still be used, but only for single line Codes without the whole selector
> 
> false:
> ```css
> //.main-section {
> //  -webkit-box-shadow: 0 0 8px 1px rgba(0,0,0,0.49);
> //  -moz-box-shadow: 0 0 8px 1px rgba(0,0,0,0.49);
> //  box-shadow: 0 0 8px 1px rgba(0,0,0,0.49);
> //  margin: 12px 0 20px;
> //}
> ```
> right:
> ```css
> /*.main-section {
>   -webkit-box-shadow: 0 0 8px 1px rgba(0,0,0,0.49);
>   -moz-box-shadow: 0 0 8px 1px rgba(0,0,0,0.49);
>   box-shadow: 0 0 8px 1px rgba(0,0,0,0.49);
>   margin: 12px 0 20px;
> /*}
> ```
> right:
> ```css
> .main-section {
> //  -webkit-box-shadow: 0 0 8px 1px rgba(0,0,0,0.49);
> //  -moz-box-shadow: 0 0 8px 1px rgba(0,0,0,0.49);
> //  box-shadow: 0 0 8px 1px rgba(0,0,0,0.49);
> //  margin: 12px 0 20px;
> }
> ```
